// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RLwukdll1_nTYmfo4mZktFtzmzvnqog',
    appId: '1:472449562161:web:f65b7137bc287b7baf0710',
    messagingSenderId: '472449562161',
    projectId: 'fir-crud-produits',
    authDomain: 'fir-crud-produits.firebaseapp.com',
    storageBucket: 'fir-crud-produits.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZVQTmMX3ZiGQoSBP66u6klBS44f8JvQ',
    appId: '1:472449562161:android:96cb7e6a8c96eaa6af0710',
    messagingSenderId: '472449562161',
    projectId: 'fir-crud-produits',
    storageBucket: 'fir-crud-produits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxaL7S4_usPiMAB597iiu8QIy_M2pJrA',
    appId: '1:472449562161:ios:7997a6cd0bb652faaf0710',
    messagingSenderId: '472449562161',
    projectId: 'fir-crud-produits',
    storageBucket: 'fir-crud-produits.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxaL7S4_usPiMAB597iiu8QIy_M2pJrA',
    appId: '1:472449562161:ios:7997a6cd0bb652faaf0710',
    messagingSenderId: '472449562161',
    projectId: 'fir-crud-produits',
    storageBucket: 'fir-crud-produits.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1RLwukdll1_nTYmfo4mZktFtzmzvnqog',
    appId: '1:472449562161:web:93c7a1f60e29d726af0710',
    messagingSenderId: '472449562161',
    projectId: 'fir-crud-produits',
    authDomain: 'fir-crud-produits.firebaseapp.com',
    storageBucket: 'fir-crud-produits.firebasestorage.app',
  );

}